#!/usr/bin/env bash
# =============================================================================
# ensemble-ctl.sh — ENSEMBLE CAST 管理コマンド
#
# 鑑賞ルーム(Theater)の Ctrl+b → M メニューから呼ばれる。手動実行も可。
#
# Usage: bash scripts/ensemble-ctl.sh <command> [--wait]
#   restart       全体再起動（ensemble kill → launch-ensemble.sh）
#   restart-live  LIVE画面のみ再起動（show-live.sh を再実行）
#   status        セッション状態表示
#   checkpoint    チェックポイント保存
# =============================================================================
set -euo pipefail

PROJECT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Colors
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# --wait フラグ（popup から呼ばれた場合に Enter 待ち）
WAIT=false
CMD="${1:-help}"
shift || true
for arg in "$@"; do
  [ "$arg" = "--wait" ] && WAIT=true
done

wait_if_needed() {
  if [ "$WAIT" = true ]; then
    echo ""
    read -rp "  Enter で閉じる "
  fi
}

# ========================================
# restart — 全体再起動
# ========================================
cmd_restart() {
  echo -e "${YELLOW}"
  echo "  ┌──────────────────────────────────────┐"
  echo "  │  🔄 ENSEMBLE 全体再起動              │"
  echo "  └──────────────────────────────────────┘"
  echo -e "${NC}"

  if tmux has-session -t ensemble 2>/dev/null; then
    echo -e "  ${DIM}現在の ensemble セッションを終了します...${NC}"
    tmux kill-session -t ensemble 2>/dev/null || true
    echo -e "  ${GREEN}✓ セッション終了${NC}"
    sleep 1
  else
    echo -e "  ${DIM}ensemble セッションは存在しません${NC}"
  fi

  echo ""
  echo -e "  ${CYAN}launch-ensemble.sh を起動します...${NC}"
  echo ""
  bash "$PROJECT_PATH/launch-ensemble.sh"

  # theater セッションが存在すれば LIVE 画面も再起動
  if tmux has-session -t theater 2>/dev/null; then
    echo ""
    echo -e "  ${CYAN}LIVE 画面を再起動します...${NC}"
    sleep 2
    cmd_restart_live
  fi
}

# ========================================
# restart-live — LIVE 画面のみ再起動
# ========================================
cmd_restart_live() {
  local left_pane
  left_pane=$(tmux list-panes -t theater -F '#{pane_id} #{pane_title}' 2>/dev/null \
    | grep 'THEATER' | awk '{print $1}' || true)

  if [ -z "$left_pane" ]; then
    tmux display-message "❌ THEATER ペインが見つかりません" 2>/dev/null \
      || echo "Error: THEATER pane not found"
    return 1
  fi

  # 現プロセスを Ctrl-C で停止
  tmux send-keys -t "$left_pane" C-c
  sleep 1

  # show-live.sh を再起動（2コール）
  tmux send-keys -t "$left_pane" "bash ${PROJECT_PATH}/scripts/show-live.sh --interactive"
  sleep 0.3
  tmux send-keys -t "$left_pane" Enter

  tmux display-message "📺 LIVE 再起動しました" 2>/dev/null || true
}

# ========================================
# status — 状態確認
# ========================================
cmd_status() {
  echo -e "${CYAN}"
  echo "  ┌──────────────────────────────────────┐"
  echo "  │  📊 ENSEMBLE STATUS                  │"
  echo "  └──────────────────────────────────────┘"
  echo -e "${NC}"

  # Ensemble session
  echo -e "  ${BOLD}Ensemble Session${NC}"
  if tmux has-session -t ensemble 2>/dev/null; then
    tmux list-panes -t ensemble -F '    #{pane_id}  #{pane_title}  (#{pane_current_command})' 2>/dev/null
  else
    echo -e "    ${RED}セッションなし${NC}"
  fi
  echo ""

  # Theater session
  echo -e "  ${BOLD}Theater Session${NC}"
  if tmux has-session -t theater 2>/dev/null; then
    tmux list-panes -t theater -F '    #{pane_id}  #{pane_title}  (#{pane_current_command})' 2>/dev/null
  else
    echo -e "    ${RED}セッションなし${NC}"
  fi
  echo ""

  # Dashboard summary
  echo -e "  ${BOLD}Dashboard (先頭20行)${NC}"
  if [ -f "$PROJECT_PATH/dashboard.md" ]; then
    head -20 "$PROJECT_PATH/dashboard.md" | sed 's/^/    /'
  else
    echo -e "    ${DIM}dashboard.md なし${NC}"
  fi
  echo ""

  # Activity log (最新5行)
  echo -e "  ${BOLD}Activity Log (最新5件)${NC}"
  if [ -f "$PROJECT_PATH/logs/activity.log" ] && [ -s "$PROJECT_PATH/logs/activity.log" ]; then
    tail -5 "$PROJECT_PATH/logs/activity.log" | sed 's/^/    /'
  else
    echo -e "    ${DIM}ログなし${NC}"
  fi
  echo ""
}

# ========================================
# checkpoint — チェックポイント保存
# ========================================
cmd_checkpoint() {
  echo -e "${CYAN}"
  echo "  ┌──────────────────────────────────────┐"
  echo "  │  💾 チェックポイント保存              │"
  echo "  └──────────────────────────────────────┘"
  echo -e "${NC}"

  local TIMESTAMP
  TIMESTAMP=$(date "+%Y-%m-%dT%H:%M:%S")
  local checkpoint_file="$PROJECT_PATH/queue/checkpoint.yaml"

  # dashboard.md を丸ごとスナップショット
  local dashboard_content="(なし)"
  if [ -f "$PROJECT_PATH/dashboard.md" ]; then
    dashboard_content=$(sed 's/^/    /' "$PROJECT_PATH/dashboard.md")
  fi

  cat > "$checkpoint_file" << CPEOF
# ENSEMBLE CAST — チェックポイント
# Generated by ensemble-ctl.sh
checkpoint:
  timestamp: "$TIMESTAMP"
  reason: "Manual checkpoint via ensemble-ctl"
  dashboard_snapshot: |
${dashboard_content}
CPEOF

  echo -e "  ${GREEN}✓ 保存完了${NC}: queue/checkpoint.yaml"
  echo -e "  ${DIM}タイムスタンプ: $TIMESTAMP${NC}"
}

# ========================================
# Dispatch
# ========================================
case "$CMD" in
  restart)      cmd_restart;      wait_if_needed ;;
  restart-live) cmd_restart_live                 ;;
  status)       cmd_status;       wait_if_needed ;;
  checkpoint)   cmd_checkpoint;   wait_if_needed ;;
  help|*)
    echo ""
    echo "  Usage: ensemble-ctl.sh <command> [--wait]"
    echo ""
    echo "  Commands:"
    echo "    restart       全体再起動（ensemble kill → 再起動）"
    echo "    restart-live  LIVE画面のみ再起動（show-live.sh）"
    echo "    status        セッション状態表示"
    echo "    checkpoint    チェックポイント保存"
    echo ""
    echo "  Theater から: Ctrl+b → M でメニュー表示"
    echo ""
    wait_if_needed
    ;;
esac
